### ISSUE TITLE
When click on Upload Records in member login no response and getting this error

### ISSUE THREAD

**Issue by junaid2314** [Primechain/blockchain-ekyc-sawtooth#1]
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at fetch.then.then (/usr/src/blockchain-ekyc-sawtooth/sawtooth-ekyc-member/jsclient/BlockchainLib/storage.js:92:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:5889) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Storage.getKycCategoriesFromBlockchain (/usr/src/blockchain-ekyc-sawtooth/sawtooth-ekyc-member/jsclient/BlockchainLib/storage.js:79:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:5889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)

**Comment by rahul0812** [comment]
You have not uploaded category details in the blockchain. Run "category.sh" file, it will add those details. Please refer to "eKYC Application - single node setup" in setup file.
If you still face any errors, do let me know.

**Comment by junaid2314** [comment]
Still facing issue same issue after running  category.sh and my setup is "eKYC Application - single node setup"

root@hyperledger-sawtooth:/usr/src/blockchain-ekyc-sawtooth/sawtooth-ekyc-member# bash category.sh 
[13:41:29 INFO    connectionpool] Starting new HTTP connection (1): localhost
[13:41:29 DEBUG   connectionpool] "POST /batches HTTP/1.1" 202 184
Response: {
  "link": "http://localhost:8008/batch_statuses?id=fbc6d731e8b938ebbbd615e39d470e6794b571dc4f2c441dba6df189a1cb27cf77cf06c15067b0126216833dc0a79139ac24da8b6b3df877f25990ea0d6ff272"
}

**Comment by rahul0812** [comment]
We need to check few things here, can you please mail me at tiwarirahul7991@gmail.com. It will be easy for us to solve this issue quickly.

**Comment by junaid2314** [comment]
Its working now after performing 7th step and running category.sh script again 
Thank you So much Rahul for you support.

**Comment by rahul0812** [comment]
Welcome. Closing the issue as resolved.

**Comment by gamertwo1** [comment]
@junaid2314 @rahul0812  I'm getting same error

/jsclient$ node kycMember.js
(node:7816) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Server up on port 2309
(node:7816) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at fetch.then.then (/home/bukc/blockchain-ekyc-sawtooth/sawtooth-ekyc-member/jsclient/BlockchainLib/storage.js:92:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:7816) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Storage.getKycCategoriesFromBlockchain (/home/bukc/blockchain-ekyc-sawtooth/sawtooth-ekyc-member/jsclient/BlockchainLib/storage.js:79:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:7816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


I've tried running bash.category again but no luck. Repeat all steps 

bash.category gives 

[14:39:32 INFO    connectionpool] Starting new HTTP connection (1): localhost
[14:39:32 DEBUG   connectionpool] "POST /batches HTTP/1.1" 202 184
Response: {
  "link": "http://localhost:8008/batch_statuses?id=991215a2ea27c10b1df55c278c9ee34dbac36ab91334ce93bb5203cb311a678e3d38cb3dc0610368c60b3526ce4d8a25b6f1c95a2db51a998a816ede9c7b5630"
}
[14:39:32 INFO    connectionpool] Starting new HTTP connection (1): localhost
[14:39:32 DEBUG   connectionpool] "POST /batches HTTP/1.1" 202 184
Response: {
  "link": "http://localhost:8008/batch_statuses?id=270aa6a10fdb92365144e1b39898b2bb2e0a15dc648644567fcf21758f7ca6284cda60a8aa6bf2505f9b73504d5f832c410f08cf7703936329eea0127f97ddbf"

.x.x.x..x.x
